jobs:
  applications:
    name: Unit Test EA
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Git Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      id: download-jdk
      name: Download JDK ${{ matrix.java-version }} from jdk.java.net
      uses: oracle-actions/setup-java@v1
      with:
        release: ${{ matrix.java-version }}
        website: jdk.java.net
    - continue-on-error: true
      name: Print outputs
      run: 'echo ''Outputs''

        echo "steps.download-jdk.outputs.archive = ${{ steps.download-jdk.outputs.archive
        }}"

        echo "steps.download-jdk.outputs.version = ${{ steps.download-jdk.outputs.version
        }}"

        '
      shell: bash
    - continue-on-error: true
      name: Set Maven Wrapper
      run: mvn -N wrapper:wrapper -Dmaven=3.6.3 --no-transfer-progress
    - continue-on-error: true
      name: JDK Version
      run: java --version
    - continue-on-error: true
      env:
        MAVEN_OPTS: -Xmx2g
      name: Javadoc
      run: ./mvnw -Dsurefire.useFile=false -DskipTests -Denforcer.skip=true clean
        install javadoc:aggregate -pl '!unit-tests,!serialization-tests,!jcstress-tests,!junit-trait-runner,!unit-tests-java8,!test-coverage,!p2-repository,!org.eclipse.collections:org.eclipse.collections'
        --no-transfer-progress
    strategy:
      fail-fast: false
      matrix:
        java-version:
        - 23
        os:
        - ubuntu-latest
name: JDK-EA Javadoc
on:
  repository_dispatch:
    types: trigger-ga___earlyaccess-javadoc.yml
