jobs:
  applications:
    env:
      JAVA_VERSION: ${{ matrix.java-version }}
    name: Unit Test ${{ matrix.java-version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Git Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set Maven Wrapper
      run: mvn -N wrapper:wrapper -Dmaven=3.6.3 --no-transfer-progress
    - continue-on-error: true
      name: Set JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      env:
        MAVEN_OPTS: -Xmx1g
      name: Unit-Test
      run: ./mvnw verify --no-transfer-progress
    strategy:
      matrix:
        java-version:
        - 11
        os:
        - ubuntu-latest
name: Unit tests
on:
  repository_dispatch:
    types: trigger-ga___unit.yml
